### ISSUE TITLE
[ycb] VTK files of tetrahedral meshes 

### ISSUE THREAD

**Issue by DamrongGuoy** [RobotLocomotion/models#24]
I'd like to create and maintain tetrahedral meshes in VTK files for YCB objects.

1. Decimate the fine triangle meshes in existing Obj files to make temporary coarser triangle meshes.
2. Create tetrahedral meshes from coarse triangle meshes.
3. Fix tetrahedral meshes to remove tetrahedral elements with zero signed-distance gradients. (related Drake PR [19232](https://github.com/RobotLocomotion/drake/pull/19232))
4. Save into VTK files for compliant-hydroelastic objects and deformable objects.
5. Use them in Drake's new hydroelastic tutorials for non-convex compliant-hydroelastic meshes (TODO: companion Drake PR).

**Comment by jwnimmer-tri** [comment]
> Use them in Drake's new hydroelastic tutorials for non-convex compliant-hydroelastic meshes (TODO: companion Drake PR).

Was that referring to https://github.com/RobotLocomotion/drake/pull/20774?

If yes, then it seems you decided to use the non-convex pepper instead of a YCB object; is that right?

If yes, then I wonder if there is still any reason to convert add any volume meshes for YCB objects?  Please clarify whether we still need this enhancement or not.

**Comment by DamrongGuoy** [comment]
We can close it now.  Thanks for checking.
